// experimental/angular_projects/projects/Dominion-dev/src/app/home.component.ts
import { Component, OnInit } from '@angular/core';
import { RN } from 'rnjs';

import { UserService } from './database/user.service';


@Component({
  selector: 'app-home',
  template: `
    <div class="body-with-padding">
      <app-list appName="Dominion Apps" [apps]="apps$ | async" > </app-list>
    </div>
  `,
  styles: [],
})
export class HomeComponent implements OnInit {

  apps$: RN<{
      routerLink:  string,
      inService:   boolean,
      title:       string,
      subtitle:    string,
      description?: string
    }[]>;

  constructor(
    private user: UserService
  ) {
    this.apps$ = this.user.signedIn$.map( signedIn => [
        {
          routerLink: '/online-game',
          inService:  signedIn,
          title:      'Online Game',
          subtitle:   'Dominion オンライン対戦',
          description: `※Chrome推奨${( signedIn ? '' : '、要ログイン')}`,
        },
        {
          routerLink: '/online-randomizer',
          inService:  signedIn,
          title:      'Randomizer Online',
          subtitle:   'サプライ生成＆ゲーム結果追加（グループ同期機能付き）',
          description: `※Chrome推奨${( signedIn ? '' : '、要ログイン')}`,
        },
        {
          routerLink: '/game-result',
          inService: signedIn,
          title: 'Game Result List',
          subtitle: '成績表',
          description: ( signedIn ? '' : '※要ログイン'),
        },
        { routerLink: '/cardlist' , inService: true, title: 'Card List', subtitle: 'カード一覧表', },
        { routerLink: '/rulebooks', inService: true, title: 'RuleBooks', subtitle: 'Dominionのルールブック(PDF)', },
      ] );
  }

  ngOnInit() {
  }
}

// experimental/dominion_app/src/components/home.tsx
import React, { memo } from 'react'
import { Link } from 'react-router-dom'
import * as I from 'immutable'
import { Card, CardContent, Typography } from '@material-ui/core'

import { main } from '../constants/default-styles'

const apps: I.List<{
  route: string
  title: string
  subtitle: string
  description: string
}> = I.List([
  {
    route: '/randomizer',
    title: 'Randomizer',
    subtitle: 'サプライ生成＆ゲーム結果追加（グループ同期機能付き）',
    description: '※Chrome推奨'
  },
  {
    route: '/game-result',
    title: 'Game Result',
    subtitle: '成績表',
    description: ''
  },
  {
    route: '/card-list',
    title: 'Card List',
    subtitle: 'カード一覧表',
    description: ''
  },
  {
    route: '/rulebooks',
    title: 'Rulebooks',
    subtitle: 'Dominionのルールブック(PDF)',
    description: ''
  }
])

const css = {
  box: {
    margin: '20px'
  },
  card: {
    width: '100%'
  },
  wrapper: {
    display: 'flex',
    flexFlow: 'row wrap',
    justifyContent: 'flex-start',
    alignItems: 'flex-end',
    alignContent: 'flex-start'
  }
}

export const Home = memo(() => (
  <div style={main}>
    {apps.map(app => (
      <div key={app.title} style={css.box}>
        <Card style={css.card}>
          <Link to={app.route}>
            <CardContent>
              <Typography variant='h5' component='h2'>
                {app.title}
              </Typography>
              <Typography component='p'>{app.subtitle}</Typography>
              <Typography component='p'>{app.description}</Typography>
            </CardContent>
          </Link>
        </Card>
      </div>
    ))}
  </div>
))

Home.displayName = 'Home'
