// experimental/dominion_app/src/components/dominion/game-results/game-result-list/game-result-list.tsx
import * as I from 'immutable'
import { memo, useCallback, useState } from 'react'
import {
  ColumnSetting,
  DataTable,
  ICellPosition,
  SortState,
  TableSettings,
} from 'react-data-table'
import { useRNValue } from 'rnjs-hooks'
import * as fbc from '~/firebase/firebase-combined-values'
import * as fb from '~/firebase/firebase-worker'
import { GameResult, TGameResult } from '~/types/game-result'
import { GameResultDialog } from '../../sub-components/game-result-dialog/game-result-dialog'

const settings = TableSettings({
  displayNo: false,
  usepagination: true,
  itemsPerPageInit: 25,
  itemsPerPageOptions: I.List([25, 50, 100, 200, 400]),
  sortInit: SortState({ activeColumnId: 0, activeCellState: 'desc' }),
  columnSettings: I.List([
    ColumnSetting({
      label: '日付',
      sort: 'number',
    }),
    ColumnSetting({
      label: '場所',
      filterType: 'select',
    }),
    ColumnSetting({
      label: '順位（クリックすると詳細を表示します）',
      align: 'left',
      isButton: true,
    }),
  ]),
})

const toYMDslashed = (e: string) => {
  const date = new Date(e)
  return `${date.getFullYear()}/${date.getMonth() + 1}/${date.getDate()}`
}

export const GameResultList = memo(
  ({
    gameResultsFiltered,
  }: Readonly<{
    gameResultsFiltered: I.List<TGameResult>
  }>) => {
    const table = gameResultsFiltered.map((gr) =>
      I.List([
        toYMDslashed(gr.date),
        gr.place,
        gr.players.map((p) => `${p.rank}. ${p.name}(${p.VP})`).join('，'),
      ])
    )

    const [dialogIsOpen, setDialogIsOpen] = useState<boolean>(false)

    const [selectedGameResult, setSelectedGameResult] = useState<TGameResult>(
      GameResult()
    )

    const closeDialog = useCallback(() => {
      setDialogIsOpen(false)
    }, [setDialogIsOpen])

    const cellClick = useCallback(
      (pos: ICellPosition) => {
        setSelectedGameResult(
          gameResultsFiltered.get(pos.rowIndex, GameResult())
        )
        setDialogIsOpen(true)
      },
      [gameResultsFiltered, setDialogIsOpen, setSelectedGameResult]
    )

    const expansions = useRNValue(fb.expansions$)
    const cardIdToDCardProperty = useRNValue(fbc.cardIdToDCardProperty$)

    return (
      <>
        <DataTable table={table} settings={settings} cellClick={cellClick} />
        <GameResultDialog
          isOpen={dialogIsOpen}
          closeDialog={closeDialog}
          gameResult={selectedGameResult}
          expansions={expansions}
          cardIdToDCardProperty={cardIdToDCardProperty}
        />
      </>
    )
  }
)

GameResultList.displayName = 'GameResultList'

// experimental/angular_projects/projects/Dominion-dev/src/app/dominion/game-result/game-result-list.component.ts
import { Component, Input, OnInit } from '@angular/core';
import { MatDialog } from '@angular/material';
import { RN, manual } from 'rnjs';
import { FireDatabaseService } from '../../database/database.service';
import { CellPosition } from '../../mylib/data-table/types/cell-position';
import { TableSettings } from '../../mylib/data-table/types/table-settings';
import { GameResultDetailDialogComponent } from '../sub-components/game-result-detail-dialog/game-result-detail-dialog.component';
import { SetMemoDialogComponent } from '../sub-components/set-memo-dialog.component';
import { GameResult } from '../types/game-result';

@Component({
  selector: 'app-game-result-list',
  template: `
    <ng-container
      *ngIf="{
        GRlistFiltered: GRlistFiltered$ | async,
        table: table$ | async,
      } as data"
    >
      <div class="body-with-padding">
        <app-data-table
          [table]="data.table"
          [settings]="settings"
          (clickedCellPosition)="cellOnClick($event, data.GRlistFiltered)"
        >
        </app-data-table>
      </div>
    </ng-container>
  `,
})
export class GameResultListComponent implements OnInit {
  GRlistFiltered$ = manual<GameResult[]>([]);

  @Input() set gameResultListFiltered(value: GameResult[]) {
    if (!value) return;
    this.GRlistFiltered$.emit(value);
  }

  settings = new TableSettings({
    displayNo: true,
    usepagination: true,
    itemsPerPageInit: 25,
    itemsPerPageOptions: [25, 50, 100, 200, 400],
    sortInit: { active: '0', direction: 'desc' },
    headerSettings: [
      {
        displayName: '日付',
        align: 'c',
        sort: true,
        transform: (e: number) => {
          const date = new Date(e);
          return `${date.getFullYear()}/${
            date.getMonth() + 1
          }/${date.getDate()}`;
        },
      },
      {
        displayName: '場所',
        align: 'c',
        filterType: 'select',
        sort: true,
      },
      {
        displayName: 'スコア',
        align: 'c',
        makeSubTable: true,
        subTableHeader: [
          { name: 'Rank', width: 'narrow' },
          { name: 'Name', width: 'normal' },
          { name: 'VP', width: 'narrow' },
          { name: 'Score', width: 'narrow' },
        ],
      },
      {
        displayName: 'メモ',
        align: 'c',
        isButton: true,
      },
      {
        displayName: '詳細',
        align: 'c',
        isButton: true,
      },
    ],
  });

  table$!: RN<any[][]>;

  constructor(
    public dialog: MatDialog,
    private database: FireDatabaseService,
  ) {
    this.table$ = this.GRlistFiltered$.map((GRlist) =>
      GRlist.map((gr) => [
        gr.date,
        gr.place,
        gr.players.map((grpl) => [grpl.rank, grpl.name, grpl.VP, grpl.score]),
        'memo',
        'Detail',
      ]),
    );
  }

  ngOnInit() {}

  cellOnClick(position: CellPosition, GRlist: GameResult[]) {
    switch (position.columnIndex) {
      case 3:
        this.editMemo(GRlist[position.rowIndex]);
        break;
      case 4:
        this.showDetail(GRlist[position.rowIndex]);
        break;
      default:
        break;
    }
  }

  private editMemo(gameResult: GameResult) {
    const dialogRef = this.dialog.open(SetMemoDialogComponent);
    dialogRef.componentInstance.memo = gameResult.memo;
    dialogRef.afterClosed().subscribe((result) => {
      if (result === undefined) return;
      this.database.gameResult.setMemo(gameResult.databaseKey, result);
    });
  }

  private showDetail(gameResult: GameResult) {
    const dialogRef = this.dialog.open(GameResultDetailDialogComponent, {
      autoFocus: false,
    });
    dialogRef.componentInstance.gameResult = gameResult;
  }
}
