// experimental/my_spa_framework_dev/sample/src/App.svelte
<script>
	let name = 'world';
	let num = 2;
	$: suffix = new Array(num).fill("!").join("");
	$: msg = `${name}${suffix}`;

	const increment = () => { num = num + 1; }
	const decrement = () => { num = Math.max(0, num - 1); }
</script>

<h1>Hello {msg}</h1>
<button on:click={increment}>+1</button>
<button on:click={decrement}>-1</button>

// experimental/learn_svelte_with_react/src/App.js
import React, { useState, useMemo } from 'react';

function App() {
  const name = 'world';

  const [num, setNum] = useState(2);

  const suffix = useMemo(() => new Array(num).fill('!').join(''), [num]);
  const msg = useMemo(() => `${name}${suffix}`, [name, suffix]);

  return (
    <div className='App'>
      <h1>Hello {msg}</h1>
      <button onClick={() => setNum((x) => x + 1)}>{'+1'}</button>
      <button onClick={() => setNum((x) => Math.max(0, x - 1))}>{'-1'}</button>
    </div>
  );
}

export default App;
