// experimental/angular_projects/projects/Dominion-dev/src/app/dominion/game-result/game-result-of-player.component.ts
import { Component, OnInit, Input } from '@angular/core';

import { RN, combine, manual } from 'rnjs';

import { utils } from '../../mylib/utilities';
import { GameResult } from '../types/game-result';
import { TableSettings } from '../../mylib/data-table/types/table-settings';
import { getAllPlayerGR } from './functions/get-all-player-gr';
import { PlayerGR } from './types/player-gr';


@Component({
  selector: 'app-game-result-of-player',
  template: `
    <div class="body-with-padding">
      <app-data-table
        [table]='table$ | async'
        [settings]='settings$ | async'>
      </app-data-table>
    </div>
  `,
  styleUrls: [ '../../mylib/data-table/data-table.component.css' ]
})
export class GameResultOfPlayerComponent implements OnInit {

  private GRListFiltered$ = manual<GameResult[]>([]);
  @Input() set gameResultListFiltered( value: GameResult[] ) {
    if ( !value ) return;
    this.GRListFiltered$.emit( value );
  }

  settings$!: RN<TableSettings>;
  table$!: RN<any[][]>;


  constructor( ) { }

  ngOnInit() {

    const GRofEachPlayerForView$: RN<PlayerGR[]>
      = this.GRListFiltered$
          .map( GRlist => getAllPlayerGR( GRlist ) );

    const nofRankOption$: RN<number[]>
      = this.GRListFiltered$
          .map( list =>
            utils.array.maxValue( list.map( e => e.players.length ) ) )
          .map( m => utils.number.numSeq( 1, m ))
          .withInitialValue( utils.number.numSeq( 1, 4 ) );

    this.settings$ = nofRankOption$.map( nofRankOption =>
      new TableSettings({
      displayNo      : false,
      usepagination  : false,
      sortInit       : { active: '1', direction: 'asc' },
      headerSettings : [
        {
          align       : 'c',
          sort        : true,
          displayName : '名前',
        }, {
          sort        : true,
          displayName : '平均得点',
          transform   : e => utils.number.roundAt( e, 3 ).toString(),
          compareFn   : utils.number.cmpR,
        }, {
          sort        : true,
          displayName : '総得点',
          transform   : e => utils.number.roundAt( e, 3 ).toString(),
          compareFn   : utils.number.cmpR,
        }, {
          sort        : true,
          displayName : '総対戦回数',
          compareFn   : utils.number.cmpR,
        },
        ...nofRankOption.map( i => ({
            sort        : true,
            displayName : `${i}位回数`,
            compareFn   : utils.number.cmpR,
          }),
        )
      ],
    }));


    this.table$
      = combine( GRofEachPlayerForView$, nofRankOption$ )
          .map( ([list, nofRankOption]) =>
            list.map( obj => [
              obj.name,
              obj.scoreAverage,
              obj.scoreSum,
              obj.count,
              ...nofRankOption.map( i => obj.countRank[i] )
            ])
          );

  }
}

// experimental/dominion_app/src/components/dominion/game-results/game-result-of-player/game-result-of-player.tsx
import React, { memo } from 'react'
import * as I from 'immutable'

import * as num from 'typescript-utils/functions/number'
import {
  TableSettings,
  DataTable,
  ColumnSetting,
  SortState
} from 'react-data-table'

import { TGameResult } from '~/types/game-result'
import { allPlayerGameResults } from './all-player-game-results'

const numRankOption = I.List(num.numSeq(1, 6))

export const GameResultOfPlayer = memo(
  ({
    gameResultsFiltered
  }: Readonly<{
    gameResultsFiltered: I.List<TGameResult>
  }>) => {
    const settings = TableSettings({
      displayNo: false,
      usepagination: false,
      sortInit: SortState({ activeColumnId: 1, activeCellState: 'asc' }),
      columnSettings: I.List([
        ColumnSetting({
          align: 'center',
          sort: 'string',
          label: '名前'
        }),
        ColumnSetting({
          sort: 'number-reverse',
          label: '平均得点',
          cellToStr: e => num.roundAt(e, 3).toString()
        }),
        ColumnSetting({
          sort: 'number-reverse',
          label: '総得点',
          cellToStr: e => num.roundAt(e, 3).toString()
        }),
        ColumnSetting({
          sort: 'number-reverse',
          label: '総対戦回数'
        })
      ]).concat(
        numRankOption.map(i =>
          ColumnSetting({
            sort: 'number-reverse',
            label: `${i}位回数`
          })
        )
      )
    })

    const table = allPlayerGameResults(gameResultsFiltered).map(obj =>
      I.List([obj.name, obj.scoreAverage, obj.scoreSum, obj.count]).concat(
        numRankOption.map(i => obj.numEachRank.get(i))
      )
    )

    return <DataTable table={table} settings={settings} />
  }
)

GameResultOfPlayer.displayName = 'GameResultOfPlayer'
