// packages/apps/slack_app/src/index.tsx
import ReactDOM from 'react-dom';
import './index.css';
import { Main } from './main';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(<Main />, document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();

// experimental/solid_tutorial/src/index.tsx
import 'solid-js';
import { render } from 'solid-js/dom';
import { App } from './App';
import './index.css';
import * as serviceWorker from './serviceWorker';

render(App, document.getElementById('root') as Node);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
