// experimental/packages/apps/lambda-calculus-interpreter-react/src/components/app.tsx
import {
  outputAreaString$,
  setInputAreaString,
  useInputAreaString,
} from '../state';
import { CodeArea } from './code-area';

export const App = memoNamed('App', () => {
  const inputAreaString = useInputAreaString();
  const outputAreaString = useObservableValue(outputAreaString$);

  return (
    <div
      css={css`
        padding: 10px;
        min-height: 100vh;
      `}
    >
      <h2>{'(Untyped) lambda calculus'}</h2>
      <div
        css={css`
          padding: 10px;
        `}
      >
        {'expr ::= x | (lambda x. expr) | (expr expr)'}
      </div>
      <TextAreaWrapper>
        <div>{'Input:'}</div>
        <CodeArea
          cyId={'input-area'}
          maxHeightPx={500}
          minHeightPx={100}
          value={inputAreaString}
          valueChange={setInputAreaString}
        />
      </TextAreaWrapper>

      <TextAreaWrapper>
        <div>{'Output:'}</div>
        <CodeArea
          cyId={'output-area'}
          maxHeightPx={800}
          minHeightPx={500}
          value={outputAreaString ?? 'Parse error.'}
        />
      </TextAreaWrapper>
    </div>
  );
});

const TextAreaWrapper = styled.div`
  padding: 10px;
  width: 100%;
`;

// packages/apps/lambda_calculus_interpreter_solid/src/components/App.tsx
import { styled } from '@noshiro/solid-styled-components';
import { JSX } from 'solid-js';
import { useStateAsStream, useStreamValue } from '../utils';
import { CodeArea } from './code-area';
import { toLambdaEvaluated } from './to-lambda-eval-operator';

const inputAreaStringInitialValue: string = '((+ 2) 3)';

export const App = (): JSX.Element => {
  const [inputAreaString$, setInputAreaString] = useStateAsStream<string>(
    inputAreaStringInitialValue
  );

  const inputAreaString = useStreamValue(
    inputAreaString$,
    inputAreaStringInitialValue
  );

  const outputAreaString$ = inputAreaString$.pipe(toLambdaEvaluated);

  const outputAreaString = useStreamValue(outputAreaString$, '');

  return (
    <Root>
      <Title>(Untyped) lambda calculus</Title>
      <Description>expr ::= x | (lambda x. expr) | (expr expr)</Description>
      <TextAreaWrapper>
        <div>Input:</div>
        <InputAreaStyled
          value={inputAreaString}
          valueChange={setInputAreaString}
        />
      </TextAreaWrapper>

      <TextAreaWrapper>
        <div>Output:</div>
        <OutputAreaStyled value={outputAreaString} />
      </TextAreaWrapper>
    </Root>
  );
};

const Root = styled('div')`
  padding: 10px;
`;

const Title = styled('h2')``;

const Description = styled('div')`
  padding: 10px;
`;

const TextAreaWrapper = styled('div')`
  padding: 10px;
  width: 100%;
`;

const CodeAreaStyled = styled(CodeArea)`
  /* max-width: 100%;
  min-width: 600px; */
  width: 100%;
`;

const InputAreaStyled = styled(CodeAreaStyled)`
  min-height: 100px;
  max-height: 500px;
`;

const OutputAreaStyled = styled(CodeAreaStyled)`
  min-height: 500px;
  max-height: 800px;
`;
