// packages/apps/lambda_calculus_interpreter/src/index.tsx
import React from 'react';
import ReactDOM from 'react-dom';
import { Main } from './components/main';
import './index.css';
import * as serviceWorker from './serviceWorker';

ReactDOM.render(<Main />, document.getElementById('root'));

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();

// packages/apps/lambda_calculus_interpreter_solid/src/index.tsx
import 'solid-js';
import { render } from 'solid-js/web';
import { Main } from './components';
import './index.css';
import * as serviceWorker from './serviceWorker';

render(Main, document.getElementById('root') as Node);

// If you want your app to work offline and load faster, you can change
// unregister() to register() below. Note this comes with some pitfalls.
// Learn more about service workers: https://bit.ly/CRA-PWA
serviceWorker.unregister();
